GET https://vigilant-space-fortnight-x59wqvqj9p5qh6v57-5000.app.github.dev/api/profile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFtdcmV2ZXIxOEBnbWFpbC5jb20iLCJpYXQiOjE3MTc5NDg5Nzd9.7fGNxZScvgU8sakuacpYllJm358_VfkDSzRCRuc33yQ
